server:
  port: 5000
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true

spring:
  application:
    name: user-service
  datasource:
    hikari:
      autoCommit: false
    url: jdbc:postgresql://localhost:5433/userService
    username: postgres
    password: aylaadem233
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

info:
  application:
    name: 'user service'
    description: 'This is a user microservice for saloon booking system'
    version: '@project.version@'
